name: portfolio-dev
services:
  app:
    image: portfolio:dev-latest
    build:
      context: .
      dockerfile: docker/dev/Dockerfile
    volumes:
      - .:/home/node/app
      - /home/node/app/node_modules  # Preserve container's node_modules
    ports:
      - '3002:3000'
    environment:
      NODE_ENV: development
      NUXT_API_BASE_URL: http://host.docker.internal:3003
      NUXT_API_BASE_PATH: /api/v1
      NUXT_API_TOKEN: ${NUXT_API_TOKEN:-}
      POW_GH_TOKEN: ${POW_GH_TOKEN:-}
    user: 'node'
    extra_hosts:
      - 'host.docker.internal:host-gateway'
