name: portfolio-dev
services:
  app:
    image: portfolio:dev-latest
    build:
      context: .
      dockerfile: docker/dev/Dockerfile
    volumes:
      - .:/home/node/app
      - /home/node/app/node_modules  # Preserve container's node_modules
    ports:
      - '3001:3000'
    environment:
      NODE_ENV: development
    user: 'node'
